### PR TITLE
Revert "Modernize build system"

### PR DESCRIPTION
**Pull request by arighi**
Adjusting the build system to a more modern way is a good plan, but this change ended up introducing a few regressions in the packaging: bash completion and default config file are not shipped anymore in distro, causing some issues.

Therefore, let's revert this change for now and try to re-introduce these changes in a more incremental way, making sure that we can keep shipping all the expected files.

This has been discussed in issue #181.

### CODE REVIEW

**Comment by tamird** [comment]
Give me a few minutes please.

**Comment by arighi** [comment]
> Give me a few minutes please.

Take your time, I just pushed this to see if we could revert it cleanly. :)

**Comment by arighi** [comment]
... and thanks for looking at this!

**Comment by tamird** [comment]
Sent #183. We would still need packaging to be adjusted, but I would hope that's an easy lift for those maintainers.

**Comment by arighi** [comment]
Duplicate of #184.

**Pull request closed without merging**
